language: node_js
node_js:
  - "8"
  
cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g ganache-cli truffle
  - ganache-cli &>/dev/null &

install:
  - npm install
  - npm run setup

script:
  - NODE_ENV='production' npm run test